# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('book', models.ManyToManyField(to='app.Book')),
            ],
        ),
    ]
